  version: version-placeholder-{build}-{branch}
  cache:
    - packages -> **\packages.config
  configuration: Release
  install:
    - git submodule update --init --recursive   
  before_build:
  - ps: >-
      .\appveyor-deploy\BuildPreamble.ps1         
  build:
        verbosity: minimal
  image: Visual Studio 2015
  before_test:
  - ps: >-
      .\appveyor-deploy\TestPreamble.ps1